### PR TITLE
Sammy

### PR DESCRIPTION
**Pull request by SammyBloom**
Add story is almost done. Creating PR to be aided by ndekong.

### CODE REVIEW

**Comment by codejunk1e** [comment]
Please fix the conflicts

**Comment by SammyBloom** [comment]
Add story should be working perfectly now

**Comment by Adesire** [comment]
I guess so, did you try creating a story?

**Comment by AnthoniaOkafor** [comment]
Creating a story crashes the app, try and fix it asap @SammyBloom .

**Pull request merged**
