### PR TITLE
profile bookmark activity.

### PR DESCRIPTION
**Pull request by lettaz**
I fixed the profile bookmark activity(nothing was actually wrong with it, was a ui ish), added the story's image to the item bookmark and made it fit the figma design.

Now users can see their bookmarked story from their activity

### CODE REVIEW

**Comment by Adesire** [comment]
fix conflicts

**Comment by Adesire** [comment]
fix conflicts

**Comment by lettaz** [comment]
done

**Comment by Adesire** [comment]
Still has conflicts

**Pull request merged**
