### PR TITLE
conflicts fixed i think

### PR DESCRIPTION
**Pull request by segunfrancis**

### CODE REVIEW

**Comment by gbindinazeez** [comment]
the app is not more pulling stories from the BE database when installed

**Comment by gbindinazeez** [comment]
please create another PR ... i would not want to cause error cause i have merged some requets already

**Comment by Adesire** [comment]
You are meant to pull from dev_test and push to that, not master

**Comment by Adesire** [comment]
Please I can't merge this until you do so, also the app doesn't fetch data when I test it

**Comment by codejunk1e** [comment]
Closing this PR so we know where we are.

**Pull request closed without merging**
