### PR TITLE
User can now set a daily reminder

### PR DESCRIPTION
**Pull request by vague369**

### CODE REVIEW

**Comment by Adesire** [comment]
Build failed

**Comment by Adesire** [comment]
Error message : "Minimum supported Gradle version is 5.4.1. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in ...\android-kidstories\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

**Comment by vague369** [comment]
I don't think that's my problem though... I think you're building with 4.10.3...

**Comment by vague369** [comment]
The Gradle version has always been there, didn't touch it...

**Comment by Adesire** [comment]
My gradle version is 5.4.1

**Comment by vague369** [comment]
I'm not sure bout this, cause I assume you've been building before, but please see...

https://stackoverflow.com/questions/52145064/error-minimum-supported-gradle-version-is-4-6-in-android-studio-3-0-1/52145566

**Comment by Adesire** [comment]
image

**Comment by Adesire** [comment]
My gradle is 5.4.1

**Comment by vague369** [comment]
Is this error showing up only for my PR?

**Comment by Adesire** [comment]
Yes

**Pull request closed without merging**
