### PR TITLE
Implemented the dark mode setting feature for other activities

### PR DESCRIPTION
**Pull request by Geniuzzz**
Activities will need to extend BaseActivity for this feature to work

### CODE REVIEW

**Comment by gbindinazeez** [comment]
the app is crashing when i tested this out ...

**Comment by Geniuzzz** [comment]
at what point is it crashing?

**Comment by gbindinazeez** [comment]
It crashes immediately i run the app

**Comment by gbindinazeez** [comment]
reslove the conflict and pull request again

**Pull request closed without merging**
