### PR TITLE
Stories fixed to match new endpoint

### PR DESCRIPTION
**Pull request by Adesire**
Stories should work now, but were set to first page only

### CODE REVIEW

**Comment by vague369** [comment]
Why first page only?

**Comment by Adesire** [comment]
I hadn't worked on paginaton, this is so we can see stories to work on our various tasks, I'm still attempting pagination

**Comment by Adesire** [comment]
For example I wanted to work on search filter and I needed to view stories to be able to do so

**Comment by vague369** [comment]
Cool... Thanks

**Comment by vague369** [comment]
Where is the Data class you used from?

**Comment by Adesire** [comment]
I created it

**Comment by vague369** [comment]
See ```private Data data```

**Comment by vague369** [comment]
What's the package name?

**Comment by Adesire** [comment]
It's inside the responses package for stories

**Comment by Adesire** [comment]
> What's the package name?
story

**Comment by Adesire** [comment]
wait...i forgot to commit it

**Comment by Adesire** [comment]
I'll fix that now

**Comment by vague369** [comment]
Can't seem to locate it in the Repository

**Comment by Adesire** [comment]
Give me a minute please

**Comment by Adesire** [comment]
I forgot to git add the new class I created

**Comment by vague369** [comment]
Okay, waiting

**Comment by Adesire** [comment]
Pull now

**Comment by vague369** [comment]
Okay

**Pull request merged**
